name: 'Publish application'
on: 
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    env:
     PUBLISH_FOLDER: Blazor-PDF-js/bin/Release/net9.0/publish/wwwroot

    name: Build and Deploy Job
    steps:
      - name: Set the name of the repo in env variable 
        run: 
            echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.203'

      - name: Debug - Lister les fichiers importants
        run: |
            echo "Contenu de l’arborescence :"
            tree -L 3
            
      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # version stable Node.js
          
      - name: Install dependencies
        run: npm install

      - name: Installer TypeScript
        run: npm install -g typescript

      - name: Compiler les fichiers TypeScript
        run: tsc --project Blazor-PDF-js/tsconfig.json

      - name: Debug - Liste les fichiers
        run: |
          echo "Contenu du workspace:"
          find . -name "tsconfig.json"
    
      - name: Dotnet Publish
        run: 
            dotnet publish Blazor-PDF-js/Blazor-PDF-js.csproj --configuration Release -f net9.0
    
      - name: Change base-tag in index.html to repo name
        run: sed -i 's/<base href="\/" \/>/<base href="\/${{ env.REPO_NAME }}\/" \/>/g' $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html
  
      - name: copy index.html to 404.html
        run: cp $GITHUB_WORKSPACE/$PUBLISH_FOLDER/index.html $GITHUB_WORKSPACE/$PUBLISH_FOLDER/404.html
      
      - name: Add .nojekyll file
        run: touch $PUBLISH_FOLDER/.nojekyll
        
      - name: Deploy GitHub Pages action
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ${{ env.PUBLISH_FOLDER }}
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
