name: Remove JS from Git Tracking

on:
  workflow_dispatch:   # déclenche manuellement depuis l’interface GitHub

jobs:
  cleanup-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # pour autoriser le push

      - name: Remove .js files from git tracking
        run: |
          git rm --cached '*.js' || echo "No JS files to remove"
          git commit -m "Remove .js files from git tracking" || echo "No changes to commit"
          git push origin HEAD
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
