name: Remove Only Generated JS

on:
  workflow_dispatch:

jobs:
  cleanup-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # Important : permet de push

      - name: Configure Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Remove tracked Home.razor.js files only
        run: |
          find . -name "Home.razor.js" -exec git rm --cached {} \; || echo "No Home.razor.js files to untrack"
          git commit -m "Remove Home.razor.js from git tracking" || echo "Nothing to commit"
          git push

